FORMAT: 1A
HOST: https://dashboard.heroku.com/apps/weconnect-nesh/

# weconnect

WeConnect provides a platform that brings businesses and individuals together. This platform creates awareness for businesses and gives the users the ability to write reviews about the businesses they have interacted with. The following project contains User Interface Designs for the platform.

## User registration [/api/v1/auth/register]

### Register a user [POST]

+ Request (application/json)

        {
            "email":"user@example.com",
            "username":"user",
            "password":"user12"
        }

+ Response 201 (application/json)

    + Body
    
            {
                "message":"User Succesfully Registered"
            }